export const commands = {
  help: () => [
    "\x1b[1m\x1b[96mAVAILABLE COMMANDS\x1b[0m",
    "\x1b[36m═══════════════════════════════════════════════════════════════════\x1b[0m",
    "",
    "  \x1b[92mhelp\x1b[0m          - Show this help message",
    "  \x1b[92mwhoami\x1b[0m        - Display current user information",
    "  \x1b[92mabout\x1b[0m         - Show detailed biography",
    "  \x1b[92mskills\x1b[0m        - List technical expertise",
    "  \x1b[92mexperience\x1b[0m    - Show complete work history",
    "  \x1b[92mprojects\x1b[0m      - Display notable projects",
    "  \x1b[92mcontact\x1b[0m       - Get contact information",
    "  \x1b[92machievements\x1b[0m  - Show career achievements",
    "  \x1b[92meducation\x1b[0m     - Display educational background",
    "  \x1b[92mlanguages\x1b[0m     - Show programming languages",
    "  \x1b[92mframeworks\x1b[0m    - List frameworks and libraries",
    "  \x1b[92msecurity\x1b[0m      - Cybersecurity tools and expertise",
    "  \x1b[92mdevops\x1b[0m        - DevOps and infrastructure tools",
    "  \x1b[92mleadership\x1b[0m    - Leadership and management skills",
    "  \x1b[92mlogs\x1b[0m          - Show system logs with colors",
    "",
    "  \x1b[33m404\x1b[0m           - You found the terminal anyway!",
    "  \x1b[33m403\x1b[0m           - Access granted to terminal",
    "  \x1b[33merror\x1b[0m         - No errors here, just features",
    "",
    "\x1b[1m\x1b[97m💡 USAGE TIPS:\x1b[0m",
    "   • Type any command to get started!",
    "   • Use \x1b[93mCtrl+C\x1b[0m to cancel current input",
    "   • Use \x1b[93m↑/↓\x1b[0m arrow keys for command history",
    "",
    "\x1b[35m🌟 All routes lead to this terminal interface!\x1b[0m"
  ],

  404: () => [
    "\x1b[1m\x1b[91mHTTP 404 - NOT FOUND\x1b[0m",
    "\x1b[31m═══════════════════════════════════════════════════════════════════\x1b[0m",
    "",
    "\x1b[93m🎯 You were looking for a page that doesn't exist...\x1b[0m",
    "   \x1b[97mBut you found something better - my interactive terminal!\x1b[0m",
    "",
    "\x1b[92m💡 This entire portfolio is a single terminal interface.\x1b[0m",
    "   \x1b[97mEvery URL leads here because this IS the portfolio.\x1b[0m",
    "",
    "\x1b[96m🚀 Instead of traditional pages, use terminal commands:\x1b[0m",
    "   • Type '\x1b[92mabout\x1b[0m' to learn about me",
    "   • Type '\x1b[92mskills\x1b[0m' to see my expertise",
    "   • Type '\x1b[92mcontact\x1b[0m' to get in touch",
    "   • Type '\x1b[92mhelp\x1b[0m' to see all commands",
    "",
    "\x1b[35m🌟 This is modern portfolio design - no boring static pages!\x1b[0m",
    "",
    "\x1b[1m\x1b[92mStatus: FOUND THE BEST VERSION ✅\x1b[0m"
  ],

  403: () => [
    "\x1b[1m\x1b[93mHTTP 403 - FORBIDDEN\x1b[0m",
    "\x1b[33m═══════════════════════════════════════════════════════════════════\x1b[0m",
    "",
    "\x1b[91m🔐 Access denied? Not here!\x1b[0m",
    "   \x1b[97mWelcome to my open-source portfolio terminal.\x1b[0m",
    "",
    "\x1b[92m✅ You have FULL ACCESS to:\x1b[0m",
    "   • \x1b[97mAll professional information\x1b[0m",
    "   • \x1b[97mComplete technical expertise\x1b[0m",
    "   • \x1b[97mContact details and availability\x1b[0m",
    "   • \x1b[97mProject history and achievements\x1b[0m",
    "",
    "\x1b[95m🎯 No restrictions, no paywalls, no limits!\x1b[0m",
    "   \x1b[97mType '\x1b[92mhelp\x1b[0m\x1b[97m' to see what you can explore.\x1b[0m",
    "",
    "\x1b[1m\x1b[92mStatus: UNRESTRICTED ACCESS GRANTED 🚀\x1b[0m"
  ],

  error: () => [
    "ERROR? WHAT ERROR? 🤔",
    "═══════════════════════════════════════════════════════════════",
    "",
    "🐛 Bugs are just undocumented features!",
    "🔧 Errors are learning opportunities!",
    "💡 This terminal is error-free by design!",
    "",
    "🎯 Everything here works as intended:",
    "   • No 404s - just one awesome terminal",
    "   • No broken links - just commands",
    "   • No missing pages - everything's here",
    "",
    "🚀 Pro tip: Type 'help' to explore!",
    "",
    "Status: NO ERRORS DETECTED ✅"
  ],

  logs: () => [
    "SYSTEM LOGS - MOONSHOT TERMINAL v2.1.0",
    "═════════════════════════════════════════════════════════════════",
    "",
    "\x1b[32m[INFO]\x1b[0m  2025-08-05 16:28:42 - Terminal initialized successfully",
    "\x1b[36m[DEBUG]\x1b[0m 2025-08-05 16:28:43 - Loading user profile: moonShadow",
    "\x1b[33m[WARN]\x1b[0m  2025-08-05 16:28:44 - High skill level detected, enabling elite mode",
    "\x1b[32m[INFO]\x1b[0m  2025-08-05 16:28:45 - Portfolio data loaded: 32 languages, 50+ frameworks",
    "\x1b[94m[LOG]\x1b[0m   2025-08-05 16:28:46 - Security scan: No vulnerabilities found",
    "\x1b[35m[TRACE]\x1b[0m 2025-08-05 16:28:47 - Git status: Repository clean, 1337 commits",
    "\x1b[91m[ERROR]\x1b[0m 2025-08-05 16:28:48 - Error: Too much awesomeness detected",
    "\x1b[92m[FIXED]\x1b[0m 2025-08-05 16:28:49 - Previous error resolved: Feature not bug",
    "\x1b[36m[DEBUG]\x1b[0m 2025-08-05 16:28:50 - Loading blockchain expertise...",
    "\x1b[32m[INFO]\x1b[0m  2025-08-05 16:28:51 - Cybersecurity protocols: Active",
    "\x1b[93m[WARN]\x1b[0m  2025-08-05 16:28:52 - Warning: User may be too qualified for this role",
    "\x1b[96m[NET]\x1b[0m   2025-08-05 16:28:53 - Network status: Connected to 12 global servers",
    "\x1b[32m[INFO]\x1b[0m  2025-08-05 16:28:54 - DevOps pipeline: All green ✅",
    "\x1b[35m[TRACE]\x1b[0m 2025-08-05 16:28:55 - Performance metrics: 99.9% uptime achieved",
    "\x1b[36m[DEBUG]\x1b[0m 2025-08-05 16:28:56 - Loading project portfolio...",
    "\x1b[32m[INFO]\x1b[0m  2025-08-05 16:28:57 - Terminal ready for commands",
    "",
    "\x1b[1m\x1b[37mLegend:\x1b[0m",
    "  \x1b[32mINFO\x1b[0m  - General information",
    "  \x1b[36mDEBUG\x1b[0m - Debug messages",
    "  \x1b[33mWARN\x1b[0m  - Warnings",
    "  \x1b[91mERROR\x1b[0m - Errors (rare)",
    "  \x1b[35mTRACE\x1b[0m - Trace information",
    "",
    "Type 'help' to see available commands with \x1b[1mcolor\x1b[0m support!"
  ],

  whoami: () => [
    "\x1b[1m\x1b[96mramin_moradi (MoonShadow)\x1b[0m",
    "",
    "\x1b[93mUID:\x1b[0m           \x1b[97m1337\x1b[0m",
    "\x1b[93mGroups:\x1b[0m        \x1b[92mcto\x1b[0m,\x1b[92mdevops\x1b[0m,\x1b[92msecurity\x1b[0m,\x1b[92mblockchain\x1b[0m,\x1b[92mentrepreneur\x1b[0m",
    "\x1b[93mHome:\x1b[0m          \x1b[97m/home/moonShadow\x1b[0m",
    "\x1b[93mShell:\x1b[0m         \x1b[97m/bin/zsh\x1b[0m",
    "\x1b[93mStatus:\x1b[0m        \x1b[1m\x1b[92mELITE_DEVELOPER_MODE_ACTIVE\x1b[0m",
    "\x1b[93mExperience:\x1b[0m    \x1b[97m8+ years\x1b[0m",
    "\x1b[93mClearance:\x1b[0m     \x1b[91mMAXIMUM\x1b[0m",
    "\x1b[93mInnovation:\x1b[0m    \x1b[95mLEGENDARY\x1b[0m",
    "",
    "\x1b[96m🚀 CURRENT ROLES:\x1b[0m",
    "   • \x1b[1m\x1b[97mFounder & CEO @ OVERLORD Team Ltd.\x1b[0m",
    "   • \x1b[1m\x1b[97mCTO @ Sports Excitement\x1b[0m"
  ],

  about: () => [
    "╔══════════════════════════════════════════════════════════════════╗",
    "║                    RAMIN MORADI (MOONSHADOW)                     ║",
    "║               Founder of #0VLD LLC • IT Counselor                ║",
    "║          Entrepreneur & Investor • Startup Manager              ║",
    "║        Network/Software/Security/Data Engineer & Analyst        ║",
    "║                              🇹🇷🇮🇷                              ║",
    "╚══════════════════════════════════════════════════════════════════╝",
    "",
    "🏢 PRIMARY POSITION:",
    "   Founder @ OVERLORD Team Ltd. (#0VLD LLC) (Oct 2020 - Present)",
    "   • Main focus: Health and well-being technology initiatives",
    "   • Location: Manchester, England & Türkiye",
    "",
    "💼 REMOTE CONSULTING:",
    "   Chief Technology Officer @ Sports Excitement (Jun 2025 - Present)",
    "   • Remote consulting role",
    "   • Project, Team & Security Management",
    "   • Technical Decision Leadership",
    "   • Strategic Technology Planning",
    "",
    "🏢 ENTREPRENEURIAL VENTURES:",
    "   Founder @ OVERLORD Team Ltd. (Oct 2020 - Present)",
    "   • Health and well-being technology initiatives",
    "   • Manchester, England, United Kingdom",
    "",
    "   Co-Founder @ Zengin Holding GmbH (Sep 2019 - Feb 2023)",
    "   • Created innovative projects: Icanada, Urplaza, Wininmin",
    "   • Developed coin tap app with enhanced monetization",
    "   • Successfully led company to profitable exit",
    "",
    "💡 CAREER HIGHLIGHTS:",
    "   • 8+ years of technology leadership experience",
    "   • 30% user engagement improvement @ Sports Excitement",
    "   • 25% operational efficiency boost",
    "   • Successful entrepreneur with profitable exit",
    "   • Expert in cybersecurity, blockchain, and DevOps",
    "",
    "🌍 CURRENT LOCATION:",
    "   Primary: Türkiye & United Kingdom",
    "   Work Style: Remote & Hybrid globally",
    "",
    "Status: Ready for new challenges and innovation opportunities"
  ],

  experience: () => [
    "COMPLETE PROFESSIONAL EXPERIENCE",
    "═════════════════════════════════════════════════════════════════════",
    "",
    "🏢 Founder & CEO | OVERLORD Team Ltd. (#0VLD LLC)",
    "   📅 Oct 2020 - Present (4+ years) | 🌍 Türkiye & Manchester, England",
    "   PRIMARY POSITION - Self-employed",
    "   Contract Position",
    "   • Project, Team, Security Management",
    "   • Technical Decisions management",
    "   • Working with awesome SportsExcitement Team",
    "   • Enhanced product offerings in sports entertainment sector",
    "   • 30% improvement in user engagement",
    "   • 25% increase in operational efficiency",
    "",
    "🚀 Founder | OVERLORD Team Ltd.",
    "   📅 Oct 2020 - Present (4+ years) | 🌍 Manchester, England (Hybrid)",
    "   Self-employed",
    "   • Health and well-being technology initiatives",
    "   • Strategic business development",
    "   • Innovation leadership",
    "",
    "⚕️ Career Break",
    "   📅 Oct 2023 - Feb 2025 (1 year 5 months) | 🌍 Istanbul",
    "   • Health issues recovery period",
    "   • Personal development and recovery",
    "",
    "🎯 Chief Technology Officer | Sports Excitement (Previous)",
    "   📅 Apr 2023 - Oct 2023 (7 months) | 🌍 United States (Remote)",
    "   Contract Position (LinkedIn helped me get this job)",
    "   • Spearheaded technology strategy at Sports Excitement",
    "   • Enhanced product offerings in sports entertainment sector",
    "   • Collaborated with cross-functional teams",
    "   • Implemented innovative solutions",
    "   • Improved user engagement by 30%",
    "   • Championed robust tech infrastructure development",
    "   • Led to 25% increase in operational efficiency",
    "",
    "💼 Chief Technology Officer | Codebrik Solutions LLP",
    "   📅 Jul 2022 - May 2023 (11 months) | 🌍 Ahmedabad, Gujarat, India (Remote)",
    "   Part-time Position",
    "",
    "🔐 Network Security Specialist | Paravan Engineering",
    "   📅 Jan 2023 - Feb 2023 (2 months) | 🌍 Iran (Remote)",
    "   Part-time Position",
    "",
    "🏢 Co-Founder | Zengin holding GmbH",
    "   📅 Sep 2019 - Feb 2023 (3+ years) | 🌍 Türkiye (On-site)",
    "   Full-time Position",
    "   • Co-founded Zengin Holding GmbH",
    "   • Drove creation of innovative projects: Icanada, Urplaza, Wininmin",
    "   • Developed coin tap app enhancing user engagement",
    "   • Enhanced monetization strategies",
    "   • Successfully led company to profitable exit",
    "   • Demonstrated strong entrepreneurial skills",
    "   • Showcased market understanding",
    "",
    "🔧 DevOps Tech Lead | Codebrik Solutions LLP (Previous)",
    "   📅 Jul 2021 - Apr 2022 (10 months) | 🌍 Ahmedabad, Gujarat, India (Remote)",
    "   Part-time Position",
    "",
    "💻 Back End Developer | Sandali khabar",
    "   📅 Jun 2020 - Oct 2020 (5 months) | 🌍 Rasht, Gilan Province, Iran (On-site)",
    "   Contract Position",
    "",
    "🌐 Network Engineer | Telecommunication Company of Iran - TCI",
    "   📅 Dec 2019 - May 2020 (6 months) | 🌍 Rasht, Gilan Province, Iran (On-site)",
    "   Contract Position",
    "   • Configured and deployed Fiber FTTH and VDSL network infrastructure",
    "   • Managed iManage2000 system",
    "   • Enhanced operational efficiency and network management",
    "   • Collaborated with cross-functional teams",
    "   • Ensured seamless integration of network solutions",
    "   • Contributed to improved connectivity for customers",
    "   • Enhanced user experience in Rasht, Gilan Province",
    "",
    "🔧 DevOps Tech Lead | Gilace",
    "   📅 Aug 2016 - Aug 2019 (3+ years) | 🌍 Rasht, Gilan Province, Iran (On-site)",
    "   Full-time Position",
    "   • Led DevOps team at Gilace",
    "   • Enhanced web development processes and deployment strategies",
    "   • Collaborated closely with Hossein Mohsenkhah",
    "   • Implemented innovative solutions",
    "   • Improved system efficiency",
    "   • Developed essential web skills",
    "   • Contributed to successful launch of multiple projects",
    "   • Increased user engagement",
    "",
    "🎬 Freelance Video Editor | MehrAlborz University",
    "   📅 May 2018 - May 2019 (1+ year) | 🌍 Rasht, Gilan Province, Iran (Remote)",
    "   Freelance Position",
    "",
    "🔒 Security Technician | Iranian National Tax Administration",
    "   📅 Aug 2015 - Aug 2016 (1+ year) | 🌍 Tehran, Tehran Province, Iran (On-site)",
    "   Full-time Position",
    "",
    "👨‍💻 Intern | elmefarda",
    "   📅 Feb 2011 - Jun 2013 (2+ years) | 🌍 Tehran, Tehran Province, Iran (On-site)",
    "   Internship",
    "   • Collaborated with IT enthusiasts Ebrahim and Mohammad",
    "   • Explored innovative technology solutions",
    "   • Assisted in various projects",
    "   • Gained hands-on experience in IT and software development",
    "   • Developed foundational skills in problem-solving and teamwork",
    "   • Started at a young age"
  ],

  skills: () => [
    "┌─────────────────────────────────────────────────────────────────┐",
    "│                    COMPLETE TECHNICAL EXPERTISE                 │",
    "├─────────────────────────────────────────────────────────────────┤",
    "│ Industry Knowledge                                              │",
    "├─────────────────────────────────────────────────────────────────┤",
    "│ DevOps          Red Team         Blue Team        Cybersecurity │",
    "│ Ethical Hacking Computer Science Engineering      Software Dev  │",
    "│ Network Admin   Management       Performance Mgmt E-commerce    │",
    "│ Blockchain      Smart Contracts  Blockchain Analysis            │",
    "├─────────────────────────────────────────────────────────────────┤",
    "│ Tools & Technologies                                            │",
    "├─────────────────────────────────────────────────────────────────┤",
    "│ C               Assembly Lang    SQL             PHP            │",
    "│ Docker          AWS              JavaScript      Node.js        │",
    "│ Kubernetes      Linux            Git             MySQL          │",
    "│ Laravel         Microsoft SQL    Windows Server  Servers        │",
    "│ Linux Server    Server Arch      Solidity        Linux Kernel   │",
    "│ KVM             Kernel Prog      Go              WordPress       │",
    "│ CMS             Perl             Python          Swift           │",
    "│ Java            C#               Artificial AI                   │",
    "├─────────────────────────────────────────────────────────────────┤",
    "│ Interpersonal Skills                                            │",
    "├─────────────────────────────────────────────────────────────────┤",
    "│ Analytical Skills    Problem Solving    Personal Development    │",
    "│ Management          Leadership           Team Building           │",
    "│ Strategic Planning  Innovation Mgmt     Technical Mentoring     │",
    "└─────────────────────────────────────────────────────────────────┘",
    "",
    "📊 STATISTICS:",
    "   • 32+ Programming Languages Mastered",
    "   • 50+ Frameworks & Libraries",
    "   • 18+ Cybersecurity Tools",
    "   • 8+ Years Professional Experience",
    "   • Multiple Leadership Endorsements",
    "",
    "🎓 CERTIFICATIONS & ENDORSEMENTS:",
    "   • Computer Science (Fenerbahçe Üniversitesi)",
    "   • Multiple skill endorsements from colleagues",
    "   • Continuous learning and development"
  ],

  languages: () => [
    "PROGRAMMING LANGUAGES EXPERTISE",
    "═══════════════════════════════════════════════════════════════════",
    "",
    "🔥 EXPERT LEVEL (Daily Use):",
    "   JavaScript    Python        Java          C#            PHP",
    "   TypeScript    Go            C             C++           SQL",
    "",
    "⚡ ADVANCED LEVEL (Regular Use):",
    "   Ruby          Swift         Objective-C   Scala         Shell",
    "   Kotlin        Rust          Dart          Assembly      Solidity",
    "",
    "💡 PROFICIENT LEVEL (Project Experience):",
    "   R             Perl          Lua           Haskell       Julia",
    "   Clojure       Groovy        Elixir        Erlang        F#",
    "   Visual Basic  Fortran       Pascal",
    "",
    "📈 TOTAL COUNT: 32+ Programming Languages",
    "",
    "🎯 SPECIALIZED IN:",
    "   • Systems Programming (C, C++, Assembly)",
    "   • Web Development (JavaScript, TypeScript, PHP)",
    "   • Backend Development (Python, Java, Go)",
    "   • Mobile Development (Swift, Kotlin, Dart)",
    "   • Blockchain Development (Solidity)",
    "   • DevOps Scripting (Shell, Python)",
    "",
    "Status: Continuously learning new languages and paradigms"
  ],

  frameworks: () => [
    "FRAMEWORKS & LIBRARIES MASTERY",
    "═══════════════════════════════════════════════════════════════════",
    "",
    "🌐 WEB FRAMEWORKS:",
    "   Frontend:  React, Angular, Vue.js, Svelte, Ember.js",
    "   Backend:   Django, Flask, Laravel, Spring, Express",
    "   Full-Stack: Ruby on Rails, ASP.NET, Symfony, Next.js",
    "",
    "📱 MOBILE FRAMEWORKS:",
    "   Cross-Platform: React Native, Flutter, Xamarin, Cordova",
    "   Native iOS:     Swift UI, UIKit",
    "   Native Android: Kotlin, Java Android SDK",
    "",
    "🤖 AI/ML FRAMEWORKS:",
    "   TensorFlow    PyTorch       Keras         OpenCV",
    "   Scikit-learn  NumPy         Pandas        Matplotlib",
    "",
    "🎮 GAME DEVELOPMENT:",
    "   Unity         Unreal Engine Phaser        Three.js",
    "   WebGL         Canvas API",
    "",
    "💻 DESKTOP FRAMEWORKS:",
    "   .NET Core     Electron      Qt            Tkinter",
    "   WPF           Swing         JavaFX",
    "",
    "🎨 UI/UX LIBRARIES:",
    "   Bootstrap     Tailwind CSS  Material-UI   Ant Design",
    "   jQuery        Backbone.js   Foundation",
    "",
    "🔧 DEVELOPMENT TOOLS:",
    "   Webpack       Vite          Babel         ESLint",
    "   Prettier      Jest          Cypress       Storybook",
    "",
    "☁️ CLOUD FRAMEWORKS:",
    "   Serverless    CDK           Terraform     Pulumi",
    "   Ansible       Chef          Puppet",
    "",
    "📊 TOTAL: 50+ Frameworks & Libraries Mastered"
  ],

  security: () => [
    "CYBERSECURITY TOOLS & EXPERTISE",
    "═══════════════════════════════════════════════════════════════════",
    "",
    "🔍 NETWORK ANALYSIS:",
    "   Wireshark     Nmap          Netstat       TCPDump",
    "   Aircrack-ng   Kismet        Ettercap",
    "",
    "🛡️ PENETRATION TESTING:",
    "   Metasploit    Burp Suite    OWASP ZAP     Nikto",
    "   SQLmap        Hydra         John Ripper   Hashcat",
    "",
    "🔒 VULNERABILITY ASSESSMENT:",
    "   Nessus        OpenVAS       Qualys        Rapid7",
    "   Acunetix      Checkmarx     Veracode",
    "",
    "🐧 SECURITY DISTRIBUTIONS:",
    "   Kali Linux    Parrot OS     BlackArch     Pentoo",
    "   BackBox       DEFT Linux",
    "",
    "🔐 SECURITY FRAMEWORKS:",
    "   OWASP Top 10  NIST          ISO 27001     PCI DSS",
    "   SOC 2         GDPR          HIPAA",
    "",
    "🚨 INCIDENT RESPONSE:",
    "   Splunk        ELK Stack     SIEM          SOAR",
    "   Volatility    Autopsy       Sleuth Kit",
    "",
    "🛡️ EXPERTISE AREAS:",
    "   • Red Team Operations",
    "   • Blue Team Defense",
    "   • Ethical Hacking",
    "   • Network Security",
    "   • Blockchain Analysis",
    "   • Digital Forensics",
    "   • Security Architecture",
    "   • Compliance Management",
    "",
    "🎯 SPECIALIZATIONS:",
    "   • Advanced Persistent Threat (APT) Detection",
    "   • Zero-day Vulnerability Research",
    "   • Cryptocurrency Security Audits",
    "   • Enterprise Security Strategy"
  ],

  devops: () => [
    "DEVOPS & INFRASTRUCTURE MASTERY",
    "═══════════════════════════════════════════════════════════════════",
    "",
    "🐳 CONTAINERIZATION:",
    "   Docker        Kubernetes    Podman        LXC/LXD",
    "   OpenShift     Rancher       Docker Swarm",
    "",
    "☁️ CLOUD PLATFORMS:",
    "   AWS           Azure         Google Cloud  DigitalOcean",
    "   Heroku        Vercel        Netlify       Cloudflare",
    "",
    "🔧 CONFIGURATION MANAGEMENT:",
    "   Ansible       Terraform     Puppet        Chef",
    "   SaltStack     Vagrant       Packer",
    "",
    "🚀 CI/CD PIPELINES:",
    "   Jenkins       GitLab CI     GitHub Actions CircleCI",
    "   Azure DevOps  TeamCity      Bamboo        Drone",
    "",
    "📊 MONITORING & LOGGING:",
    "   Prometheus    Grafana       ELK Stack     Splunk",
    "   Datadog       New Relic     Nagios        Zabbix",
    "",
    "🐧 OPERATING SYSTEMS:",
    "   Linux Distributions:",
    "   • Ubuntu      • CentOS      • RHEL        • Debian",
    "   • Arch Linux  • Alpine      • CoreOS      • Amazon Linux",
    "",
    "   Windows Server:",
    "   • Active Directory • IIS     • PowerShell  • Hyper-V",
    "",
    "🗄️ DATABASES:",
    "   MySQL         PostgreSQL    MongoDB       Redis",
    "   ElasticSearch InfluxDB      Cassandra     MariaDB",
    "",
    "🌐 WEB SERVERS & PROXIES:",
    "   Nginx         Apache        HAProxy       Traefik",
    "   Cloudflare    AWS ALB       F5 BigIP",
    "",
    "🔐 SECURITY INFRASTRUCTURE:",
    "   VPN Setup     Firewall Config SSL/TLS Mgmt PKI",
    "   Identity Mgmt OAuth/SAML    Zero Trust",
    "",
    "📈 INFRASTRUCTURE AS CODE:",
    "   • Terraform for multi-cloud deployment",
    "   • Ansible for configuration management",
    "   • CloudFormation for AWS resources",
    "   • ARM templates for Azure",
    "   • Kubernetes manifests for container orchestration"
  ],

  leadership: () => [
    "LEADERSHIP & MANAGEMENT EXPERTISE",
    "═══════════════════════════════════════════════════════════════════",
    "",
    "👥 TEAM LEADERSHIP:",
    "   • Led teams of 10+ developers and engineers",
    "   • Cross-functional team coordination",
    "   • Agile/Scrum methodology implementation",
    "   • Technical mentoring and coaching",
    "   • Performance management and reviews",
    "",
    "🎯 STRATEGIC PLANNING:",
    "   • Technology roadmap development",
    "   • Digital transformation initiatives",
    "   • Budget planning and resource allocation",
    "   • Risk assessment and mitigation",
    "   • Innovation strategy implementation",
    "",
    "🏢 EXECUTIVE EXPERIENCE:",
    "   Chief Technology Officer:",
    "   • Sports Excitement (Current & Previous)",
    "   • Codebrik Solutions LLP",
    "",
    "   Founder/Co-Founder:",
    "   • OVERLORD Team Ltd. (Current)",
    "   • Zengin Holding GmbH (Successful Exit)",
    "",
    "📈 BUSINESS IMPACT:",
    "   • 30% improvement in user engagement",
    "   • 25% increase in operational efficiency",
    "   • Successful company exit with profit",
    "   • Multiple product launches",
    "   • Revenue growth through technology innovation",
    "",
    "💡 INNOVATION MANAGEMENT:",
    "   • R&D department leadership",
    "   • Emerging technology evaluation",
    "   • Patent and IP strategy",
    "   • Technology stack modernization",
    "   • Competitive analysis and positioning",
    "",
    "🎓 MENTORING & DEVELOPMENT:",
    "   • Junior developer training programs",
    "   • Technical interview processes",
    "   • Career development planning",
    "   • Knowledge sharing initiatives",
    "   • Code review and quality standards",
    "",
    "🌍 GLOBAL EXPERIENCE:",
    "   • United States (Current)",
    "   • United Kingdom (Manchester)",
    "   • Turkey (Türkiye)",
    "   • India (Remote collaboration)",
    "   • Iran",
    "",
    "🏆 ACHIEVEMENTS:",
    "   • Built and scaled technology teams",
    "   • Delivered complex enterprise projects",
    "   • Established DevOps and security practices",
    "   • Created innovation culture",
    "   • Achieved measurable business results"
  ],

  projects: () => [
    "NOTABLE PROJECTS & INNOVATIONS",
    "═══════════════════════════════════════════════════════════════════",
    "",
    "🏆 ZENGIN HOLDING ECOSYSTEM (2019-2023)",
    "   ├── 🍁 Icanada Platform",
    "   │   • Immigration and education services platform",
    "   │   • Full-stack web application",
    "   │   • Multi-language support",
    "   │",
    "   ├── 🛒 Urplaza Marketplace",
    "   │   • E-commerce platform development",
    "   │   • Payment gateway integration",
    "   │   • Vendor management system",
    "   │",
    "   ├── 🎮 Wininmin Gaming App",
    "   │   • Mobile gaming application",
    "   │   • User engagement features",
    "   │   • Monetization strategies",
    "   │",
    "   └── 💰 Cryptocurrency Tap Game",
    "       • Blockchain integration",
    "       • Token economics design",
    "       • Mobile-first development",
    "",
    "🚀 SPORTS EXCITEMENT INNOVATIONS (2023, 2025)",
    "   ├── 📈 User Engagement Platform",
    "   │   • 30% improvement in user engagement",
    "   │   • Real-time sports data integration",
    "   │   • Advanced analytics dashboard",
    "   │",
    "   ├── ⚡ Operational Efficiency System",
    "   │   • 25% increase in operational efficiency",
    "   │   • Automated workflow processes",
    "   │   • Performance monitoring tools",
    "   │",
    "   └── 🏗️ Infrastructure Modernization",
    "       • Cloud migration strategy",
    "       • Microservices architecture",
    "       • DevOps pipeline implementation",
    "",
    "🔐 CYBERSECURITY IMPLEMENTATIONS",
    "   ├── 🛡️ Enterprise Security Framework",
    "   │   • Multi-layer security architecture",
    "   │   • Zero-trust network implementation",
    "   │   • Compliance management system",
    "   │",
    "   ├── 🔍 Penetration Testing Suite",
    "   │   • Custom security assessment tools",
    "   │   • Automated vulnerability scanning",
    "   │   • Red team exercise platforms",
    "   │",
    "   └── 🌐 Network Infrastructure Hardening",
    "       • Firewall configuration optimization",
    "       • VPN and secure tunneling",
    "       • Intrusion detection systems",
    "",
    "☁️ CLOUD & DEVOPS PROJECTS",
    "   ├── 🏗️ Multi-Cloud Architecture",
    "   │   • AWS, Azure, GCP integration",
    "   │   • Disaster recovery planning",
    "   │   • Cost optimization strategies",
    "   │",
    "   ├── 🔄 CI/CD Pipeline Automation",
    "   │   • Kubernetes orchestration",
    "   │   • Container registry management",
    "   │   • Automated testing frameworks",
    "   │",
    "   └── 📊 Monitoring & Analytics Platform",
    "       • Real-time performance monitoring",
    "       • Log aggregation and analysis",
    "       • Predictive maintenance systems",
    "",
    "📱 MOBILE & WEB APPLICATIONS",
    "   ├── 🏥 Health & Wellness Platform (OVERLORD)",
    "   │   • Cross-platform mobile app",
    "   │   • Health tracking and analytics",
    "   │   • Integration with wearable devices",
    "   │",
    "   └── 🌐 Telecommunication Infrastructure",
    "       • FTTH and VDSL deployment",
    "       • Network management systems",
    "       • Customer connectivity solutions",
    "",
    "🎯 PROJECT STATISTICS:",
    "   • 50+ Successful projects delivered",
    "   • Multiple profitable exits",
    "   • Global impact across 5+ countries",
    "   • Technologies spanning web, mobile, blockchain, IoT"
  ],

  contact: () => [
    "CONTACT INFORMATION & AVAILABILITY",
    "═══════════════════════════════════════════════════════════════════",
    "",
    "📧 PRIMARY CONTACT:",
    "   Email: moon.shadow.rev@overlord.team",
    "   Phone: +905319429018",
    "   Backup: moon.shadow.rev@gmail.com",
    "",
    "🔗 PROFESSIONAL NETWORKS:",
    "   Company: overlord.team",
    "   LinkedIn: https://www.linkedin.com/in/ramin-moradi-91992621a/",
    "   GitHub: github.com/moonshadowrev",
    "   Portfolio: moonshadowrev.me",
    "",
    "🌐 ONLINE PRESENCE:",
    "   Twitter: @moonshadowrev",
    "   Instagram: @moonshadowrev",
    "   Reddit: https://www.reddit.com/user/moonshadowrev/",
    "",
    "📍 LOCATION & AVAILABILITY:",
    "   Current: Türkiye & United Kingdom",
    "   Work Style: Remote & Hybrid globally",
    "   Timezone: Flexible (UTC-8 to UTC+3)",
    "   Travel: Available for critical projects",
    "",
    "⏰ WORKING HOURS:",
    "   Monday - Friday: 9:00 AM - 6:00 PM",
    "   Weekend: Available for urgent matters",
    "   Response Time: < 24 hours (usually < 4 hours)",
    "",
    "💼 CURRENT STATUS:",
    "   Primary: Founder & CEO @ OVERLORD Team Ltd.",
    "   Secondary: Remote CTO @ Sports Excitement",
    "   Contract Work: Available",
    "   Consulting: Available",
    "",
    "🎯 SEEKING OPPORTUNITIES IN:",
    "   • C-Level Technology Leadership (CTO, CDO)",
    "   • Technology Consulting & Advisory",
    "   • Strategic Partnership Opportunities",
    "   • Innovation & R&D Leadership",
    "   • Blockchain & Cryptocurrency Projects",
    "   • Cybersecurity & Infrastructure",
    "",
    "🔒 COMMUNICATION PREFERENCES:",
    "   • Email for initial contact",
    "   • Video calls for detailed discussions",
    "   • In-person meetings for final negotiations",
    "   • Encrypted channels for sensitive discussions",
    "",
    "⚡ QUICK RESPONSE GUARANTEED:",
    "   • Technical discussions: Immediate",
    "   • Business proposals: Same day",
    "   • Partnership inquiries: Within 24 hours",
    "",
    "💡 LET'S CONNECT:",
    "   Ready to discuss how I can drive innovation",
    "   and technological excellence in your organization!"
  ],

  achievements: () => [
    "CAREER ACHIEVEMENTS & RECOGNITIONS",
    "═══════════════════════════════════════════════════════════════════",
    "",
    "🏅 LEADERSHIP ACHIEVEMENTS:",
    "   ✓ Successfully co-founded Zengin Holding GmbH (2019-2023)",
    "   ✓ Led profitable company exit with strong ROI",
    "   ✓ Founded OVERLORD Team Ltd. (2020-Present)",
    "   ✓ Current CTO at Sports Excitement (2025)",
    "   ✓ Led cross-functional teams of 10+ professionals",
    "   ✓ 8+ years of continuous technology leadership",
    "",
    "📈 BUSINESS IMPACT METRICS:",
    "   ✓ 30% improvement in user engagement @ Sports Excitement",
    "   ✓ 25% increase in operational efficiency",
    "   ✓ Multiple successful product launches",
    "   ✓ Profitable company exit (Zengin Holding)",
    "   ✓ Revenue growth through technology innovation",
    "   ✓ Cost reduction through infrastructure optimization",
    "",
    "🔐 CYBERSECURITY EXPERTISE:",
    "   ✓ Advanced penetration testing capabilities",
    "   ✓ Red team & blue team operations experience",
    "   ✓ Enterprise network security implementations",
    "   ✓ Blockchain security auditing expertise",
    "   ✓ Compliance framework implementations",
    "   ✓ Zero-day vulnerability research",
    "",
    "☁️ TECHNOLOGY MASTERY:",
    "   ✓ 32+ programming languages mastered",
    "   ✓ 50+ frameworks and libraries expertise",
    "   ✓ Multi-cloud architecture (AWS, Azure, GCP)",
    "   ✓ DevOps & infrastructure automation",
    "   ✓ Kubernetes and container orchestration",
    "   ✓ Blockchain and smart contract development",
    "",
    "🌍 GLOBAL IMPACT:",
    "   ✓ International experience across 5+ countries",
    "   ✓ Remote team leadership across time zones",
    "   ✓ Cross-cultural project management",
    "   ✓ Global technology partnerships",
    "   ✓ International compliance and standards",
    "",
    "🎓 PROFESSIONAL DEVELOPMENT:",
    "   ✓ Computer Science education (Fenerbahçe Üniversitesi)",
    "   ✓ Multiple technical skill endorsements",
    "   ✓ Continuous learning and certification",
    "   ✓ Industry conference speaker",
    "   ✓ Technical mentoring and coaching",
    "",
    "🚀 INNOVATION & ENTREPRENEURSHIP:",
    "   ✓ Created innovative projects: Icanada, Urplaza, Wininmin",
    "   ✓ Developed cryptocurrency applications",
    "   ✓ Health and wellness technology initiatives",
    "   ✓ Sports entertainment technology advancement",
    "   ✓ Multiple patent-worthy innovations",
    "",
    "🏆 RECOGNITION & ENDORSEMENTS:",
    "   ✓ LinkedIn endorsements from industry professionals",
    "   ✓ Successful collaboration testimonials",
    "   ✓ Client satisfaction and retention",
    "   ✓ Peer recognition in technology community",
    "   ✓ Industry network and partnerships",
    "",
    "📊 CAREER STATISTICS:",
    "   • 8+ Years of Professional Experience",
    "   • 3 C-Level Executive Positions",
    "   • 2 Successful Company Foundations",
    "   • 1 Profitable Company Exit",
    "   • 50+ Successful Projects Delivered",
    "   • 150+ Technologies Mastered",
    "",
    "🎯 CURRENT TRAJECTORY:",
    "   Continuing to drive innovation in technology leadership,",
    "   seeking opportunities to create transformative impact",
    "   in emerging technologies and strategic partnerships."
  ],

  education: () => [
    "EDUCATIONAL BACKGROUND & CERTIFICATIONS",
    "═══════════════════════════════════════════════════════════════════",
    "",
    "🎓 FORMAL EDUCATION:",
    "   Institution: Fenerbahçe Üniversitesi",
    "   Field: Computer Science",
    "   Specialization: Advanced Computing Systems",
    "   Academic Endorsements: Multiple skill recognitions",
    "",
    "💻 TECHNICAL CERTIFICATIONS:",
    "   • Advanced Cybersecurity Protocols",
    "   • Cloud Architecture Design (AWS, Azure)",
    "   • Kubernetes Administration",
    "   • DevOps Pipeline Management",
    "   • Blockchain Development",
    "   • Network Security Implementation",
    "",
    "🏢 PROFESSIONAL DEVELOPMENT:",
    "   • Leadership and Management Training",
    "   • Strategic Technology Planning",
    "   • Enterprise Architecture Design",
    "   • Project Management Methodologies",
    "   • Team Building and Communication",
    "",
    "📚 CONTINUOUS LEARNING:",
    "   • Daily technology research and experimentation",
    "   • Open source contribution and collaboration",
    "   • Industry conference attendance and speaking",
    "   • Technical blog writing and knowledge sharing",
    "   • Mentoring junior developers and engineers",
    "",
    "🔬 RESEARCH & DEVELOPMENT:",
    "   • Emerging technology evaluation",
    "   • Innovation prototype development",
    "   • Technical feasibility studies",
    "   • Performance optimization research",
    "   • Security vulnerability analysis",
    "",
    "🌟 SPECIALIZED TRAINING:",
    "   • Red Team / Blue Team Security Operations",
    "   • Advanced Penetration Testing Techniques",
    "   • Blockchain and Cryptocurrency Technology",
    "   • Machine Learning and AI Implementation",
    "   • Quantum Computing Fundamentals",
    "",
    "Status: Lifelong learner committed to staying at the",
    "       forefront of technological advancement"
  ]
};